myBlog/categories/urls.py
from django.conf.urls import patterns, url

from categories import views

urlpatterns = patterns('',
 #   url(r'^$', views.index, name='index'),
	# ex: /polls/5/
#	url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
#	url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
#	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<category_id>\d+)/$', views.detail, name='detail'),
)

myBlog/myBlog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myBlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^categories/', include('categories.urls', namespace="categories")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^posts/', include('posts.urls', namespace="posts")),

)

myBlog/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
 #   url(r'^$', views.index, name='index'),
	# ex: /polls/5/
#	url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
#	url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
#	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

myBlog/categories/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=30)	

    def __unicode__(self):
        return self.category

myBlog/categories/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from categories.models import Category
from posts.models import Post
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):
	template_name = 'categories/index.html'
	context_object_name = 'categories_list'

	def get_queryset(self):
		return Category.objects.order_by('-category')[:5]

def detail(request, category_id): # set to listView
	 category_posts = Post.objects.filter(categories=category_id)
	 category_name = Category.objects.get(pk=category_id)
	 content = {'category_posts':category_posts, 'category_name':category_name}
	 template_name = 'categories/detail.html'
	 return render(request, template_name, content)

myBlog/categories/templates/categories/detail.html
{% extends 'base.html' %}
{% block title %}{{category_name.category}}{% endblock %}
{% block content %}
{% for post in category_posts %}
<h1>{{ post.title }}</h1>
<h3>{{ post.created }}</h3>
<p>{{ post.text }}</p>
<div class="categories">
	<b>Tags:</b> {% for category in post.categories.all %}
		<a href="{% url 'categories:detail' category.id %}">{{ category }}</a>
	{% endfor %}
</div>
{% endfor %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% endblock %}

myBlog/categories/templates/categories/index.html
{% extends 'base.html' %}
{% block title %}Categories list{% endblock %}
{% block content %}
<h2>Categories list</h2>

{% if categories_list %}
   <ul>
    {% for category in categories_list %}
      <li> <a href="{% url 'categories:detail' category.id %}">{{ category.category }}</a></li>

    {% endfor %}
  </ul>
    
{% else %}
    <p>No categories are available.</p>
{% endif %}
{% endblock %}