myBlog/myBlog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myBlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^categories/', include('categories.urls', namespace="categories")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^posts/', include('posts.urls', namespace="posts")),

)

myBlog/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
 #   url(r'^$', views.index, name='index'),
	# ex: /polls/5/
#	url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
#	url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
#	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

myBlog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
	<div id="wrapper">
		<div id="conteiner">
		    <div id="sidebar">
		        {% block sidebar %}
		        <h3>Navigation</h3>
		        <ul>
		            <li><a href="/">Home</a></li>
		            <li><a href="/posts/">Blog</a></li>
		            <li><a href="/categories/">Categories</a></li>
		        </ul>
		        {% include "last_news.html" %}
		        {% endblock %}
		    </div>

		    <div id="content">
		        {% block content %}{% endblock %}
		    </div>
		    <div class="clearfix"></div>
		</div>
	</div>
</body>
</html>

myBlog/templates/last_news.html
<div id="last_news">
 <h3>Latest News</h3>
 <ul>
  {% for last_new in last_news %}
     <li><a href="{% url 'posts:detail' last_new.id %}">{{ last_new.title }}</a> <span style='font-size:10px;'>{{last_new.created}}</span></li>
 {% endfor %}
 </ul>
</div>